In [1]:
import tensorflow as tf

a = tf.random.normal([6,32,32,3])
b = tf.reshape(a, (6,16, -1,3))

# print(a)
print(b)


tf.Tensor(
[[[[ 5.64896911e-02 -2.19082785e+00  3.80133390e-01]
   [-3.72558832e-01  1.74468660e+00  1.98311970e-01]
   [-6.18542552e-01 -1.77765501e+00 -5.59858739e-01]
   ...
   [-1.20335662e+00 -6.73471093e-01 -1.15498340e+00]
   [ 6.11787021e-01  9.29480731e-01  2.21628487e-01]
   [-3.70002389e-01 -3.04161608e-01  8.61549735e-01]]

  [[-6.40604556e-01 -6.76684201e-01 -1.19983697e+00]
   [-5.15823960e-01 -4.95521277e-01  2.34085798e+00]
   [-2.18772247e-01  3.67615044e-01  9.39261913e-01]
   ...
   [ 2.14973617e+00 -6.67695820e-01 -2.28630090e+00]
   [ 3.17464888e-01 -1.24984527e+00  3.59985292e-01]
   [-1.19092315e-02 -6.88485682e-01  2.35389560e-01]]

  [[-2.07701540e+00 -1.00517941e+00  6.83266580e-01]
   [ 1.02411282e+00  6.36249781e-01 -7.94016361e-01]
   [-3.41432840e-02  3.00279539e-02 -1.89502454e+00]
   ...
   [ 4.14131165e-01  1.52656898e-01 -7.43108571e-01]
   [-1.52173657e-02  3.83049071e-01  1.57822147e-01]
   [-1.65360257e-01 -2.01743618e-01  2.57644802e-01]]

  ...

 

# Memo

## 變數類型
1. tf.constant
1. tf.Variable
1. tf.placeholder

## 產生tensor
1. tf.zeros()
1. tf.zeros_like()
1. tf.fill()
1. tf.random.normal()
1. tf.random.truncated_normal()
1. tf.random.uniform()

## 資料處理

### 轉換資料
1. tf.cast()

### 選取資料
1. tensor\[_array slice_\]
1. tf.gather_nd()
1. tf.gather()
1. tf.math.top_k()

### 合併/拆分 資料
1. tf.concat()
1. tf.stack()
1. tf.unstack()
1. tf.split()

### 調整組織
1. tf.reshape()
1. tf.transpose()
1. tf.expand_dims()

### 調整資料
1. tf.pad()
1. tf.clip_by_value()
1. tf.clip_by_norm()

### 分析資料
1. tf.sort()
1. tf.argsort()
1. tf.math.reduce_mean()
